mysite/authapp/urls.py
from django.urls import path
from . import views

app_name = 'authapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('detail/<user_id>/', views.detail, name='detail'),
    path('admin/<user_id>', views.admin, name='admin'),
    path('edit_user_profile/<user_id>/', views.edit_user_profile, name='edit_user_profile'),
    path('update/<user_id>/', views.update, name='update'),
    path('change_password/<user_id>/', views.change_password, name='change_password'),
    path('password_change/<user_id>/', views.change_password, name='password_change'),
    path('activate/<uidb64>/',views.activate, name='activate'),
    path('forgot_email/', views.forgot_email, name='forgot_email'),
    path('send_email/', views.send_email, name='send_email'),
    path('password_reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password_reset/<uidb64>', views.ResetPasswordView.as_view(), name='password_reset'),
    path('recover_password/', views.RecoverPasswordView.as_view(), name="recover_password"),
    path('users/', views.RegularUsersListView.as_view()),
    path('unblock/<ip>/', views.unblock, name='unblock')
]

mysite/mysite/urls.py
from django.urls import path, include

urlpatterns = [
    path('authapp/', include('authapp.urls')),
]

mysite/authapp/models.py
from django.db import models


class Role(models.Model):
    ADMIN = 1
    REGULAR_USER = 2
    ROLE_CHOICES = (
      (ADMIN, 'admin'),
      (REGULAR_USER, 'regular_user'),
    )

    id = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, primary_key=True)

    def __str__(self):
        return self.get_id_display()


class AppUser(models.Model):    
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    email = models.EmailField(max_length=50)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    birth_date = models.DateTimeField('birthday')
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    active = models.BooleanField(default=True)


class TemporaryBanIp(models.Model):
    id = models.AutoField(primary_key=True)
    ip_address = models.GenericIPAddressField("IP")
    blocked = models.BooleanField(default=True)

    def __str__(self):
        return self.ip_address


class IpRequest(models.Model):
    ip_address = models.GenericIPAddressField("IP")
    attempt_time = models.IntegerField(blank=0)

    def __str__(self):
        return self.ip_address

mysite/authapp/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from django.views.generic import View
from django.views.generic import ListView

from .models import AppUser, Role, TemporaryBanIp
from .decorators import banned_ip_address, user_logged_in, save_ip_request


from fuzzywuzzy import fuzz
from ratelimit.decorators import ratelimit


@ratelimit(key='ip', rate='2/m')
def index(request):
    return render(request, 'authapp/index.html')


def logout(request):

    return render(request, 'authapp/index.html')


class LoginView(View):

    def get(self, request):
        return render(request, 'authapp/login.html')

    @save_ip_request
    @banned_ip_address
    def post(self, request):
        try:
            user = AppUser.objects.get(
                username=request.POST['username'],
                password=request.POST['password'])
            if not user.active:
                return render(request, 'authapp/login.html', {
                    'error_message': "User account is not activated! PLease verify you email.",
                })
        except AppUser.DoesNotExist:
            return render(request, 'authapp/login.html', {
                'error_message': "Wrong username and/or password!",
            })
        else:
            if user.role == Role.REGULAR_USER:
                return HttpResponseRedirect(reverse('authapp:detail', args=(user.id,)))
            else:
                return HttpResponseRedirect(reverse('authapp:admin', args=(user.id,)))

class RegisterView(View):

    def get(self, request):
        return render(request, 'authapp/register.html')

    def post(self, request):
        try:
            user = AppUser.objects.get(
                username=request.POST['username'],
                password=request.POST['password'],
                role=Role.REGULAR_USER)
            if not user.active:
                user.delete()
            else:
                return render(request, 'authapp/login.html', {
                    'error_message': "User already exists!",
                })
        except AppUser.DoesNotExist:
            pass

        user = AppUser(
            email=request.POST['email'],
            first_name=request.POST['first_name'],
            last_name=request.POST['last_name'],
            birth_date=request.POST['birth_date'],
            username=request.POST['username'],
            password=request.POST['password'],
            role=Role(Role.REGULAR_USER)
        )

        user.save()

        send_email_to_user(user, site_domain=get_current_site(request), end_point='activate_email')

        return HttpResponse('Please confirm your email address to complete the registration')


class RegularUsersListView(ListView):
    model = AppUser
    template_name = 'appuser_list.html'


def send_email_to_user(user, site_domain, end_point):

    mail_subject = 'Activate your account!'

    message = render_to_string('authapp/'+end_point+'.html', {
        'user': user,
        'domain': site_domain.domain,
        'uid': str(urlsafe_base64_encode(force_bytes(user.password)))[2:-1],
    })
    email = EmailMessage(
        mail_subject, message, to=[user.email]
    )
    email.send()


class RecoverPasswordView(View):

    def get(self, request):
        return render(
            request,
            'authapp/recover_password_email.html')

    def post(self, request):
        try:
            user = AppUser.objects.get(email=request.POST['email'])

        except AppUser.DoesNotExist:
            return render(
                request,
                'authapp/reset_password_email.html',
                {'message': "There is no active account with this email!"}
            )

        send_email_to_user(user, site_domain=get_current_site(request), end_point='recover_pass')

        return render(request, 'authapp/login.html', {
            'message': 'Please verify you inbox. An email was send to you!'})


class ResetPasswordView(View):

    def get(self, request, uidb64=None):

        global uuid
        uuid = uidb64

        return render(
            request,
            'authapp/password_reset.html')

    def post(self, request):
        global uuid

        if request.POST['new_password'] != request.POST['new_password_confirmed']:
            return render(
                request,
                'authapp/password_reset.html',
                {'message': "Passwords do not match!"}
            )

        uid = force_text(urlsafe_base64_decode(uuid))
        user = AppUser.objects.get(password=uid)

        if fuzz.ratio(user.password, request.POST['new_password_confirmed']) > 80:
            return render(
                request,
                'authapp/password_reset.html',
                {'message': "This very similar to the old password!"}
            )
        else:
            user.password = request.POST['new_password']
            user.save()

            return render(request, 'authapp/login.html', {
                'message': "Your password has been successfully changed!",
            })


def activate(request, uidb64):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = AppUser.objects.get(password=uid)
    except(TypeError, ValueError, OverflowError, AppUser.DoesNotExist):
        user = None
    if user is not None:
        user.active = True
        user.save()
        # return redirect('home')
        return render(request, 'authapp/login.html', {
            'message': "Thank you for your email confirmation. Now you can login to your account!",
        })
    else:
        return HttpResponse('Activation link is invalid!')


def detail(request, user_id):
    user = get_object_or_404(AppUser, pk=user_id)

    return render(request, 'authapp/detail.html', {'user': user})


def send_email(request):
    try:
        user = AppUser.objects.get(email=request.POST['email'])

    except AppUser.DoesNotExist:
        return render(
            request,
            'authapp/reset_password_email.html',
            {'message': "There is no active account with this email!"}
        )

    send_email_to_user(user, site_domain=get_current_site(request), end_point='forgot_password')

    return HttpResponse('Please verify you inbox. An email was send to you with a password reset link!')


def forgot_email(request):
    return render(
        request,
        'authapp/reset_password_email.html')


uuid = None


@user_logged_in
def change_password(request, user_id):

    return render(
        request,
        'authapp/change_password.html',
        {'user_id': user_id},
        {'mesagee':"sothmfds"}
    )


@user_logged_in
def password_change(request, user_id):
    user = get_object_or_404(AppUser, pk=user_id)

    if user.password != request.POST['old_password']:
        return render(
            request,
            'authapp/change_password.html',
            {'user_id': user_id, 'message': "Wrong old password!"}
        )

    if request.POST['new_password'] != request.POST['new_password_confirmed']:
        return render(
            request,
            'authapp/change_password.html',
            {'user_id': user_id, 'message': "Passwords do not match!"}
        )

    user.save()

    return render(
        request,
        'authapp/edit_profile.html',
        {'user': user, 'message': "updated!"}
    )


@user_logged_in
def edit_user_profile(request, user_id):
    user = get_object_or_404(AppUser, pk=user_id)

    return render(
        request,
        'authapp/edit_profile.html',
        {'user': user}
    )

@user_logged_in
def update(request, user_id):
    user = get_object_or_404(AppUser, pk=user_id)

    if request.POST['first_name'] and request.POST['first_name'] != user.first_name:
        user.first_name = request.POST['first_name']
    if request.POST['last_name'] and request.POST['last_name'] != user.last_name:
        user.last_name = request.POST['last_name']
    if request.POST['email'] and request.POST['email'] != user.email:
        user.email = request.POST['email']
    if request.POST['birth_date'] and request.POST['birth_date'] != user.birth_date:
        user.birth_date = request.POST['birth_date']

    user.save()

    return HttpResponseRedirect(reverse('authapp:detail',
                                        args=(user_id,)))


def admin(request, user_id):
    global userid
    userid = user_id
    user = get_object_or_404(AppUser, pk=user_id)
    return render(
        request,
        'authapp/admin.html',
        {'users': AppUser.objects.all(), 'user': user, 'banned_ip': TemporaryBanIp.objects.values('ip_address').distinct()}
    )


def unblock(request, ip):
    TemporaryBanIp.objects.filter(ip_address=ip).delete()
    user = get_object_or_404(AppUser, pk=userid)

    return render(
        request,
        'authapp/admin.html',
        {'users': AppUser.objects.all(), 'user': user, 'banned_ip': TemporaryBanIp.objects.values('ip_address').distinct()}
    )

mysite/authapp/templates/authapp/activate_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User</title>
</head>
<body>
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'authapp:activate' uidb64=uid %}
{% endautoescape %}
</body>
</html>

mysite/authapp/templates/authapp/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Page</title>
</head>
<body>
    <h1>Welcome {{user.first_name}}</h1>
    {% include "authapp/appuser_list.html" with object_list=users %}
<br>
{% for ip in banned_ip %}
    <a href="{% url 'authapp:unblock' ip.ip_address %}">Unblock {{ip.ip_address}}</a><br><br>
    {% empty %}
        <li>No banned ip.</li>
    {% endfor %}
<br>
{% include "authapp/logout.html" %}

</body>
</html>

mysite/authapp/templates/authapp/appuser_list.html
{% block content %}
    <h2>Users</h2>
    <ul>
    {% for user in object_list  %}
        <li>
        <strong>First Name:</strong> {{ user.first_name }}<br>
        <strong>last Name:</strong> {{ user.last_name }}<br>
        <strong>Birth date:</strong> {{ user.birth_date|date }}<br>
        <strong>Email:</strong> {{ user.email }}<br>
        <strong>User type:</strong> {{ user.role }}<br>
        <a href="{% url 'authapp:edit_user_profile' user.id %}">Edit Profile!</a><br><br>
        </li>
    {% empty %}
        <li>No registered users yet.</li>
    {% endfor %}
    </ul>
{% endblock %}

mysite/authapp/templates/authapp/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change Password!</title>
</head>
<body>
<form action="{% url 'authapp:password_change' user_id%}" method="post">
    <label for="old_password"><b>Old Password</b></label>
    <input type="old_password" placeholder="Enter Old Password" maxlength="20" name="old_password" required>
    <br><br>
    <label for="new_password"><b>New Password</b></label>
    <input type="password" placeholder="Enter New Password" maxlength="20" name="new_password" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required>
    <br><br>
    <label for="new_password_confirmed"><b>Confirm Password</b></label>
    <input type="password" placeholder="Confirm Password" maxlength="20" name="new_password_confirmed" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required>
    <br><br>
    <input type="submit" value="Change password!">
</form>
<br>
{% if user_ud %}<p><strong>{{ user_id}}</strong></p>{% endif %}
</body>
</html>

mysite/authapp/templates/authapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Welcome {{user.username}}!</h1>
<p>Public info:</p>
    First Name : {{user.first_name}} <br>
    Last Name : {{user.last_name}} <br>
    Birth Date: {{user.birth_date}} <br>
    Email Date: {{user.email}} <br>
<a href="{% url 'authapp:edit_user_profile' user.id %}">Edit Profile!</a>
{% include "authapp/logout.html" %}
</body>
</html>

mysite/authapp/templates/authapp/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Profile</title>
</head>
<body>
    <!--{% include 'authapp/register.html' %} -->
    <h1>Edit Profile!</h1>
    <form action="{% url 'authapp:update' user.id %}" method="post">
        <label for="firt_name"><b>First name</b></label>
        <input type="text" placeholder="{{user.first_name}}" maxlength="20" name="first_name">
        <br><br>
        <label for="last_name"><b>Last Name</b></label>
        <input type="text" placeholder="{{user.last_name}}" maxlength="20" name="last_name">
        <br><br>
        <label for="birth_date"><b>Birth Date</b></label>
        <input type="date" name="birth_date" placeholder="{{user.birthday}}" >
        <br><br>
        <label for="email"><b>Email</b></label>
        <input type="email" name="email" placeholder="{{user.email}}">
        <br><br>
        <a href="{% url 'authapp:change_password' user.id %}">Change password!</a>
        <br><br>

        <input type="submit" value="Save!">
    </form>
{% include "authapp/logout.html" %}
</body>
</html>

mysite/authapp/templates/authapp/forgot_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forgot Password</title>
</head>
<body>
    <body>
    {% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm to reset your password,
    http://{{ domain }}{% url 'authapp:password_reset' uidb64=uid %}
    {% endautoescape %}
</body>
</html>

mysite/authapp/templates/authapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Welcome!</h1>
    {% if error_message %}<p style="color:red"><strong>{{ error_message }}</strong></p>{% endif %}
    <a href="{% url 'authapp:login' %}">Login!</a>
    <br>
    <a href="{% url 'authapp:register' %}">Register!</a>
</body>
</html>

mysite/authapp/templates/authapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
{% if error_message %}<p style="color:red"><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'authapp:login' %}" method="post">
    <label for="username"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" maxlength="20" name="username" required>
    <br><br>
    <label for="password"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" maxlength="20" name="password" required>
    <br><br>
    <input type="submit" value="Log In">
</form>
<br>
<a href="{% url 'authapp:forgot_email' %}">Forgot password!</a>
<a href="{% url 'authapp:recover_password' %}">Recover password!</a>
</body>
</html>

mysite/authapp/templates/authapp/logout.html
<a href="{% url 'authapp:logout' %}">Log out!</a>

mysite/authapp/templates/authapp/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reset Password!</title>
</head>
<body>
<form action="{% url 'authapp:password_reset' %}" method="post">
    <label for="new_password"><b>New Password</b></label>
    <input type="password" placeholder="Enter New Password" maxlength="20" name="new_password" required>
    <br>
    <label for="new_password_confirmed"><b>Confirm Password</b></label>
    <input type="password" placeholder="Confirm Password" maxlength="20" name="new_password_confirmed" required>
    <input type="submit" value="Change password!">
</form>
<br>
{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
</body>
</html>

mysite/authapp/templates/authapp/recover_pass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forgot Password</title>
</head>
<body>
    {% autoescape off %}
    Hi {{ user.username }},
    Old password: {{user.password}}
    {% endautoescape %}
</body>
</html>

mysite/authapp/templates/authapp/recover_password_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reset Password!</title>
</head>
<body>
<P>
    Please write your email!
</P>
<form action="{% url 'authapp:recover_password' %}" method="post">
    <label for="email"><b>Email</b></label>
    <input type="email" placeholder="Enter email" maxlength="40" name="email" required>
    <input type="submit" value="Send email!">
</form>
<br>
{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
</body>
</html>

mysite/authapp/templates/authapp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
{% if error_message %}<p style="color:red"><strong>{{ error_message }}</strong></p>{% endif %}
<div>
    <form action="{% url 'authapp:register' %}" method="post">
        <label for="firt_name"><b>First name</b></label>
        <input type="text" placeholder="Enter first name" maxlength="20" name="first_name" required>
        <br><br>
        <label for="last_name"><b>Last Name</b></label>
        <input type="text" placeholder="Enter Last Name" maxlength="20" name="last_name" required>
        <br><br>
        <label for="username"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" maxlength="20" name="username" required>
        <br><br>
        <label for="password"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" maxlength="20" name="password" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required>
        <br><br>
        <label for="birth_date"><b>Birth Date</b></label>
        <input type="date" name="birth_date" required>
        <br><br>
        <label for="email"><b>Email</b></label>
        <input type="email" name="email">
        <br><br>
        <input type="submit" value="Register">
    </form>
</div>

</body>
</html>